name: Update Docker Hub Description

on:
  push:
    branches: [ "main", "feat/update/dockerhub-readme" ]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  release:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ github.repository }}
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
